# Generated by Django 5.0.6 on 2024-07-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_mail',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_phone',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
